[level]
name = "Example Level"
descriptions = ["This is an example level created using Hybroid"]
information = "https://github.com/pewpewlive/hybroid"
entry_point = "level.hyb"
casual = true

[project]
name = "example-level"
output_directory = "out"
target = "ppl"
