name: Go
on:
  push:
    branches: [ "master" ]
    paths: [ "**.go", "**.hyb" ]
  pull_request:
    branches: [ "master" ]
    paths: [ "**.go", "**.hyb" ]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'

    - name: Validate Build
      run: go build -v ./...

    - name: Validate Tests
      run: go test -v ./...
